import Navbar from '@/components/navbar';
import './globals.css';
// import { Inter } from 'next/font/google';
import 'react-slideshow-image/dist/styles.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.min.css';
import 'swiper/css';
import 'swiper/css/autoplay';
import Sidebar from '../components/sidebar';
import { Providers } from './provider';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'EienVault - The forefront of the digital revolution in the art world',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-gray-100 dark:bg-neutral-950">
        <Providers>
          <Navbar />
          <Sidebar />
          <main className="relative">{children}</main>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </Providers>
      </body>
    </html>
  );
}
