import Navbar from '@/app/components/navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './provider';
import 'react-slideshow-image/dist/styles.css';
import 'swiper/css';
import 'swiper/css/autoplay';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="min-h-full px-4 pb-16 pt-4 sm:px-6 sm:pb-20 lg:px-16 xl:pb-24">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
