'use client'
import Navbar from '@/components/navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './provider';
import 'react-slideshow-image/dist/styles.css';
import 'swiper/css';
import 'swiper/css/autoplay';
import Footer from '../components/footer/main';
import Sidebar from '../components/sidebar';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className + ' bg-gray-100'}>
        <ProgressBar
          height="4px"
          color="#f34054"
          options={{ showSpinner: true }}
          shallowRouting
        />
        <Providers>
          <Navbar />
          <Sidebar />
          <main className="relative bg-gray-100">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
