import Navbar from '@/components/navbar';
import '@/app/globals.css';
// import { Inter } from 'next/font/google';
import { Providers } from '@/app/provider';
import 'react-slideshow-image/dist/styles.css';
import 'swiper/css';
import 'swiper/css/autoplay';
import Footer from '@/components/footer/main';
import Sidebar from '@/components/sidebar';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.min.css';
import { NavbarAdmin, SidebarAdmin } from '@/components/navbar/admin';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'EienVault - The forefront of the digital revolution in the art world',
  description: 'Generated by create next app',
};

export default function AdminLayout({ children }) {
  return (
    <div className="flex justify-between gap-5">
      <NavbarAdmin />
      <SidebarAdmin />
      <section className="mt-20 w-full m-5 overflow-x-hidden block">{children}</section>
    </div>
  );
}
